### ISSUE TITLE
Controller am "Drachen"

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/Sensornetz-Flugwindkraftwerk#1]
Hier können Ideen rein, welchen Controller wir am Drachen selbst verwenden. Herr Brovkov schlug ja vor, einen mit guter Sendeleistung zu nehmen und diesen mit Sensoren zu bestücken, da diese in der Regel über vielfältigere Anschlussmöglichkeiten verfügen.

**Comment by Tomatenbiss** [comment]
Brauchen auf jeden Fall ein GPS Modul, die kleinen Boards (zB TI CC3200 oder das  STM32F401) lassen sich über UART ansprechen. Dementsprechend kann also ein kostengünstiger Empfänger angeschafft werden.

**Comment by Kaleidostar** [comment]
Wie schon an anderer stelle ausgeführt bin ich nicht begeistert von dem STM32F401.

Da Hr.Brovkov wie du schon sagtest lieber eine muc Lösung will (kann ich verstehen er will das sicher auch noch in anderen Kursen benutzen) wäre ich klar für CC3200 plus einen Satz CC1310 und dann die gewünschten Sensoren noch dazu.

**Comment by Tomatenbiss** [comment]
Warum bist du für den CC1310 und nicht den CC115L? Der CC1310 erscheint mir sehr komplex im Vergleich. Habs grad nur überflogen, weil ich gleich los muss, liegts am Stromverbrauch?

**Comment by Tomatenbiss** [comment]
Hier mal der aktuelle Stand..

Günstige Variante:
ST Microelectronics SMT32F4 Nucleo + TI CC1110 Mini Development Kit Transceiver + Weitere Sensoren
