### ISSUE TITLE
Atmel

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/Sensornetz-Flugwindkraftwerk#11]

**Comment by s0544317** [comment]
Ich hätte hier ein Starter Kit, dass die Frequenzen 315MHz, 433MHz, und 868MHz unterstützt.

Es enthält einen Sender und einen Empfänger.

Problem, diese Kit gibt es nicht mehr zu kaufen. 

http://www.atmel.com/tools/atastk512-ek1_ek2_ek3-ind.aspx
