### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/Sensornetz-Flugwindkraftwerk#2]
Hier können Ideen rein, wie und ob wir das Backend gestalten wollen. Mein Vorschlag wäre ja das skalierbare Backend www.parse.com zu nutzen (nur bis zu einer gewissen Leistung kostenfrei), müsste man halt mal schauen, ob das unseren Ansprüchen genügt oder gar zu viel ist. SDKs gibt es von parse für alle gängigen Betriebssysteme und die bekannteren Miktrocontroller (Raspberry Pie, TI CC3200, Arduino, etc.).

**Comment by UnitedUgali** [comment]
Das klingt gut. Hat da schon jemensch Erfahrung mit?

**Comment by Tomatenbiss** [comment]
Ich selber nicht, ein Kommilitone von mir aber und der scheint erstmal schwer begeistert zu sein.
