### ISSUE TITLE
Controller an der Bodenstation

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/Sensornetz-Flugwindkraftwerk#3]
Hier können Ideen rein, mit welchem Controller wir die Signalverarbeitung umsetzen wollen. Beispielsweise ein Raspberry Pie oder als mobilere Variante das CC 3200 Launchpad o.Ä..

**Comment by Kaleidostar** [comment]
Der Pie hätte den Vorteil leichter(? JavaScript experte kam ja wohl letzte Woche hinzu aber die machen wohl was anderes...) programmierbar zu sein und enorme Leistung bereitzustellen(brauchen wir die?) um die Daten zu verarbeiten.
Ich würde mich nach Sichtung der Spezifikationen sehr für den CC 3200 aussprechen.
Der Pie wäre bei größer Installationen ganz nett um die Daten von vielen Bodenstationen zusammenzufassen und ansprechend zu präsentieren(Webinterface)
das würde dann so aussehen:
Sensor(Drache)==~433Hz==>CC3200==Wifi/Inet==>DatenbankService*==Wifi/Inet==>Pie==>Webinterface (schönmitklickibunti)

*wie auch immer geartet(lokal/cloud,lite/Xhtml,Parse.com, o. Ä.)

Sollte man im hinterkopf behalten, je nach dem wie weit wir kommen.
Ich würde es aber nicht mit in die Anforderungen aufnehmen.

CodeQuelle fürs CC3200: https://github.com/remixed123

**Comment by Tomatenbiss** [comment]
Bin auch für den CC 3200. Allerdings könnte man den Schritt mit dem RaspPie sogar auslassen, da der CC 3200 ja Internet On Chip bereit stellt, also direkt alles an nen Server weiterleiten oder gar selber bereit stellen kann(!). Da wir aber einen zur Verfügung haben würde ich vorschlagen, dass zu besprechen, nachdem wir den Radiokanal etabliert haben.

**Comment by Tomatenbiss** [comment]
Hier mal der aktuelle Stand..

günstige Variante:
TI CC3200 Launchpad + TI CC1110 Mini Development Kit Transceiver

**Comment by UnitedUgali** [comment]
Was beim Raspberry Pi Modell B, was wir haben ankommen kann.

![raspberry-pi-rev2-gpio-pinout](https://cloud.githubusercontent.com/assets/15212166/11171278/914afd76-8bec-11e5-9739-79d8776b1370.jpg)

**Comment by UnitedUgali** [comment]
Das ist ein relativ einfaches Tutorial, wie Mensch die einzelnen Pins auslesen kann. die Ausgabe erfolgt dann jeweils in 0 und 1, 0, wenn auf dem Pin gerade nichts kommt und 1, wenn etwas kommt. Diese Ausgaben müssen wir dann wahrscheinlich in einem Shellscript irgendwie verwerten. Das dort beschriebene Tool "wiringPi" habe ich bereits installiert.
https://klenzel.de/1841

**Comment by Tomatenbiss** [comment]
Sauber! Genau so was brauchen wir.
