### ISSUE TITLE
SMT32F401

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/Sensornetz-Flugwindkraftwerk#4]
Hier können interessante Webressourcen zum SMT32F401 rein

**Comment by Tomatenbiss** [comment]
Etliche Beispiele für kleine Hacks. Die meisten aus dem Drohnenbereich, was uns ja ziemlich in die Hände spielt.

http://stm32f4-discovery.com/

**Comment by Tomatenbiss** [comment]
Von der obigen Seite der GitHub-Accout. Quelltext en masse.

https://github.com/MaJerle/stm32f429

**Comment by Kaleidostar** [comment]
Ich habe mir das SMT32F401 jetzt angeschaut und bin nicht begeistert sehr bescheidende toolchain dafür zumindest c++ libs, man merkt irgendwie das sie ihre 3k Boards zusammengestrichen haben bis es mit den preis hinhaut, den Rest hat man dann der Community überlassen.
Dein link ist für das Discovery das hat einen doppelt so schnellen Prozessor und mehr speicher, als der Nucleo...

**Comment by Tomatenbiss** [comment]
Wusste nicht mehr genau, welches wir zur Verfügung hatten.. Woran erkennst du die Zusammenstreicherei? Fehlende Doku/Quelltexte? 

Bin auch nicht zwingend Fan von SM Electronics. Man findet halt kaum Ressourcen. Da ist TI schon um einiges besser strukturiert.
