### ISSUE TITLE
GPS - Diskussion

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/Sensornetz-Flugwindkraftwerk#5]
Wie seht ihr eigentlich das Problem mit der Ungenauigkeit von GPS? Hab mal ein wenig recherchiert und bin zu dem Schluss gekommen, dass GPS eine Genaugkeit von 3-10 Metern leisten kann. Alternativ wäre ein (kostenintensives) DGPS denkbar. 

Halte letzteres für schwer umsetzbar im Rahmen des Projekts. Wie sehr ihr die Problematik? Sollten uns eh erstmal darauf konzentrieren, einen Radiokanal zu bauen, der die nötige Distanz von 400-500 Metern überbrücken kann.

**Comment by Kaleidostar** [comment]
GPS ist eigentlich gar nicht nötig insofern die Anwendung wie von uns besprochen auf im größeren Stil erfolgt da jeder Drache und jede Bodenstation einen Sender/Empfänger hat daher könnte man anhand der dBm die Position triangulieren im solo Einsatz (1 Station 1 Drache) geht das dann natürlich nicht.

Ich stimme dir dahingehend zu erstmal eine Kommunikationskanal zu etablieren, da wir laut Hr. Brovkov nur Modellarbeiter leisten. Im konkreten Fall würde man dann eh Platinen mit den entsprechender Sensoren/Chips bestellen die genau nur das abdecken was man möchte ( und bezahlen will )[sind dann auch viel kleiner/leichter].

**Comment by Tomatenbiss** [comment]
Wär halt schön, wenns von 1 Station bis n Station skalierbar ist, aber das ist dann alles Zukunftsmusik und sollte in dem Projekt für dieses Semester (vorerst) keine Rolle spielen. Stimme dir also voll zu.

**Comment by Tomatenbiss** [comment]
Hier hatten wir ja am Dienstag genug diskutiert. Nettes Extra, falls bezahlbar.
