### ISSUE TITLE
Module zuschalten

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/Sensornetz-Flugwindkraftwerk#6]
Wie siehts aus, hat jemand von euch schonmal mehrere Module zusammengeschaltet? Sind die erstmal steckbar oder braucht man dazu so ein Board (leider keine Ahnung, wie das heißt) zum Verbinden? Im Netz findet man alles mögliche zu den Schnittstellen und Protokollen, was schonmal sehr gut ist. Solche Basics allerdings nicht. Wäre mal gut zu wissen, damit man nicht tausend Sachen einzeln bestellen muss, sondern einmalig eine vollständige Liste anlegen kann.

**Comment by Tomatenbiss** [comment]
Frage beantwortet: http://www.conrad.de/ce/de/product/1182194/Raspberry-Pi-Verbindungskabel-Bunt-RB-CB3-50-Raspberry-Pi?ref=searchDetail

**Comment by Kaleidostar** [comment]
Herr Brovkov hat mir mit dem Arduino eine Steckplatine gegeben die könnte man ja nutzen, ansonsten kannst du alles mit einem stück twistet-Pair(Kupferdraht) zusammen schließen, da braucht es nix besonderes.

**Comment by Tomatenbiss** [comment]
Klingt Easy!
