### ISSUE TITLE
Bestellung

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/Sensornetz-Flugwindkraftwerk#8]
Ich habe mal Proben bei Texas Instruments bestellt. Je 5 Stück von den folgenden Geräten:

CC1120RHBR (Sehr gut erweiterbar mit dem CC1190 - Megareichweite/Störsicherheit)
CC1190RGVR (Das ist ein Front-End, also im Endeffekt ein Verstärker, der mit dem 1120 genutzt werden kann. Damit haben die in offenem Gelände über 100km Entfernung überbrücken können. Klingt erstmal wie mit Spatzen auf Kanonen werfen, in urbanem Gebieten haben die aber mit der Kombo "nur" 1 km erreicht. Kostet nicht viel und hat ne Hammermäßige Übertragung, also Optimal, wenn mehrere Stationen in Einsatz kommen)

CC115LRGPR (Transmitter)
CC113LRGPR (Receiver)

CC1310F128RGZR (Lässt sich auch mit dem 1190 erweitern)

**Comment by UnitedUgali** [comment]
(So hab mein Schlaptop jetzt wieder aus der Reparatur zurück und kann jetzt auch meine Produktivität wieder in der Bib steigern (so von 0 auf 5% oder so :P ).

Das scheinen mir ja nur Chips zu sein. Können wir die mit diesen weissen  Steckplatinen bereits verwenden und ansteuern?

**Comment by Tomatenbiss** [comment]
Na vor allem über den CC 3200. Darauf die Programmierung und per Schnittstelle die Zusatzmodule ansteuern. Die Steckplatinen helfen, damit wir erstmal ohne Löten auskommen.
